server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
